// firebaseConfig.ts
export const NEXT_PUBLIC_FB_API_KEY = process.env.NEXT_PUBLIC_FB_API_KEY;
export const NEXT_PUBLIC_FB_AUTH_DOMAIN =
  process.env.NEXT_PUBLIC_FB_AUTH_DOMAIN;
export const NEXT_PUBLIC_FB_PROJECT_ID = process.env.NEXT_PUBLIC_FB_PROJECT_ID;
export const NEXT_PUBLIC_FB_STORAGE_BUCKET =
  process.env.NEXT_PUBLIC_FB_STORAGE_BUCKET;
export const NEXT_PUBLIC_FB_MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_FB_MESSAGING_SENDER_ID;
export const NEXT_PUBLIC_FB_APP_ID = process.env.NEXT_PUBLIC_FB_APP_ID;
export const NEXT_PUBLIC_MEASUREMENT_ID = process.env.NEXT_PUBLIC_MEASUREMENT_ID